### ISSUE TITLE
Using UMAP and Bokeh for the project

### ISSUE THREAD

**Issue by souravsingh** [SweetiePi/bioncd-hackseq#1]
I propose using UMAP as well as bokeh for plotting and visualization. UMAP could be useful to see the representation of sequences in a 2D space. The code for UMAP is available here- https://github.com/lmcinnes/umap

UMAP is shown to be faster than t-SNE, but requires a package which could break the package- Numba.

Bokeh would be useful for adding interactivity in the plots.

**Comment by souravsingh** [comment]
I am interested to know what you think @SweetiePi

**Comment by SweetiePi** [comment]
@souravsingh Looks promising! I've never used either tool before, what advantage would UMAP give over something like matplot?

**Comment by Benjamin-Lee** [comment]
Bokeh is a great tool; I've used it in multiple bioinformatics projects and it never fails to delight me with its ease of use and flexibility.

**Comment by souravsingh** [comment]
@Sweetie-Pi UMAP is not a plotting tool. It is a dimension reduction algorithm, similar to t-SNE or PCA. I proposed this since it could be useful to learn the structure of the data and how they are distributed.

**Comment by SweetiePi** [comment]
@souravsingh I see... definitely worth considering!

**Comment by souravsingh** [comment]
As for Bokeh, I could find this- https://bokeh.pydata.org/en/latest/docs/gallery.html

Bokeh uses Javascript to render plots, so they are really interactive in nature
