### ISSUE TITLE
Investigate use of Snappy for compression

### ISSUE THREAD

**Issue by souravsingh** [SweetiePi/bioncd-hackseq#2]
Snappy claims being a faster compression algorithm(faster than LZO, LZF), so it would be interesting to investigate Snappy for genomic data.

**Comment by SweetiePi** [comment]
One goal of this project is that I want to include a LOT of compression algorithms that users of this pipeline can choose as they see fit. Some compressors sacrifice speed for a better compression ratio, while others are faster but don't compress as well. Typically the faster algorithms do well for viruses, less so for bacteria. 

Snappy is definitely worth checking out. As we lead up to the hackathon start I'll set up a list of compression tools that I want to test and potentially integrate into our pipeline.

**Comment by souravsingh** [comment]
Sweet! I was thinking of having something like `algorithm='lzma'` to initialize the algorithm.
