### ISSUE TITLE
Get sequence reverse compliment

### ISSUE THREAD

**Issue by SweetiePi** [SweetiePi/bioncd-hackseq#4]
We're working with nucleotide sequences, so we should take into account that DNA has a forward strand and a reverse strand. We should have 3 options:

- Use forward sequences only
- Use reverse sequences only
- Best of forward & reverse sequences

[BioPython](https://biopython.org/) might work really well for this.

**Comment by souravsingh** [comment]
I would also suggest looking at [scikit-bio](http://scikit-bio.org) as well for the purpose.

**Comment by tamario** [comment]
Done
