### ISSUE TITLE
Think of an alternative name for BioNCD

### ISSUE THREAD

**Issue by SweetiePi** [SweetiePi/bioncd-hackseq#42]
Throw your ideas here

**Comment by souravsingh** [comment]
BioCompress
NAC- No Alignment Comparison

**Comment by Benjamin-Lee** [comment]
If we're going with NAC as a substring we want, that opens plenty of nice options:

cognac
nacho
snack
knicknack
barnacle
spinach

**Comment by SweetiePi** [comment]
SNACC - Sequence Non-Alignment Compress & Compare
BIO SNAC - Biological Sequence Non-Alignment Comparator

**Comment by souravsingh** [comment]
I like the name BIO SNAC

**Comment by SweetiePi** [comment]
I'm leaning towards SNAC. I think having bio as a prefix is a bit redundant.

**Comment by Benjamin-Lee** [comment]
Snacc it is!
