### ISSUE TITLE
Explore BWT-Disk as a compression algorithm

### ISSUE THREAD

**Issue by SweetiePi** [SweetiePi/bioncd-hackseq#44]

**Comment by wilcas** [comment]
@SweetiePi I found a competitor's binary to BWT-Disk: [ParaBWT](http://parabwt.sourceforge.net/homepage.htm#latest) This may be a good alternative if the algorithm is hard to implement from scratch

**Comment by souravsingh** [comment]
ParaBWT requires Intel TBB, which is quite tricky to install.

**Comment by wilcas** [comment]
Got it. I found the BWT disk libraries, which claims to only need GCC

**Comment by wilcas** [comment]
So it looks like BWT-Disk does BWT in DISK memory and then it specifies the types of compression you can apply, should I create a set of options specific to this algorithm? @SweetiePi  @Benjamin-Lee

**Comment by wilcas** [comment]
running bwt disk, but integration into cli is still not done
