### ISSUE TITLE
Parse FASTA file information

### ISSUE THREAD

**Issue by SweetiePi** [SweetiePi/bioncd-hackseq#6]
Would like to store line 1 as metadata. If there are multiple sequences per fasta file (see ebola virus data), then we would like to compute NCD on all of them.

**Comment by Benjamin-Lee** [comment]
[pyfaidx](https://github.com/mdshw5/pyfaidx) is a nice way to parse FASTA files (beyond Bio.SeqIO)

**Comment by wilcas** [comment]
So you mean to say we want a way to take sequences from a fasta so we can pipe it into a compression algorithm?

**Comment by Benjamin-Lee** [comment]
Yes, exactly

**Comment by wilcas** [comment]
@SweetiePi Do we want to make everything pipeable? like each stage is a stand alone script and we can pipe the output to different stages?

**Comment by souravsingh** [comment]
[scikit-bio](http://scikit-bio.org) could also be a useful tool for this.

**Comment by SweetiePi** [comment]
@wilcas Yes, everything pipeable would be great.

**Comment by tamario** [comment]
I will take this issue and combine it with issue #4

**Comment by Benjamin-Lee** [comment]
closed by #36
