### ISSUE TITLE
Suggestion: Make a submission to JOSS

### ISSUE THREAD

**Issue by souravsingh** [SweetiePi/bioncd-hackseq#64]
I would suggest making a submission to JOSS- https://joss.theoj.org once the hackseq event finishes and we make some fixes and add tests to the code.

**Comment by Benjamin-Lee** [comment]
I would be happy with this. Other options are a Bioinformatics application note, Algorithms for Molecular Biology workflow, RECOMB paper, or (long shot) introducing the method as a full length research paper.

**Comment by SweetiePi** [comment]
I will also be happy with JOSS. hackseq has offered to reimburse the cost of submitting to f1000, but I'd prefer JOSS. As for a conference such as RECOMB, I will discuss with my PI.
