### ISSUE TITLE
Paralellize compression 

### ISSUE THREAD

**Issue by SweetiePi** [SweetiePi/bioncd-hackseq#7]
Compressing our sequences is the bottleneck of our pipeline. We want to find a way to parallelize this. Python might not be the best way to go about this due to the global interpreter lock, Cython or a Python API to another language would be interesting to look into. There are also multithreading options available in Python.

**Comment by souravsingh** [comment]
I would also suggest looking into numba- http://numba.pydata.org/

Numba uses JIT to accelerate scientific code. The only problem would be the llvmlite dependency to use Numba(which could lead to increase in binaries sizes) and could bring out problems.

**Comment by souravsingh** [comment]
@SweetiePi How should I help on this?

**Comment by SweetiePi** [comment]
@souravsingh First we need a script that takes multiple sequences at a time. Then we can look into parallelizing these sequences.

For testing, use the hackseq2 server that I linked in our Slack.

**Comment by SweetiePi** [comment]
#15 
Once that's done we can look into this

**Comment by wilcas** [comment]
Running multiple threads and cores buddies
