### ISSUE TITLE
Investigate GenCompress

### ISSUE THREAD

**Issue by SweetiePi** [SweetiePi/bioncd-hackseq#8]
[GenCompress](http://www.cs.cityu.edu.hk/~cssamk/gencomp/GenCompress1.htm) is a compression algorithm specifically designed for biological sequence data. It would be great to get a working implementation into our pipeline for testing.

**Comment by wilcas** [comment]
update: found a windows executable from the original authors as well as a linux exexutable [here](http://www1.spms.ntu.edu.sg/~chenxin/GenCompress/). It appears to require a reference genome, but the windows exec does not. Reading into the paper to get input/outputs and see if this is useful for us

**Comment by wilcas** [comment]
@SweetiePi the binary they have expects a fasta format, should I investigate re-implementing the algorithm

**Comment by wilcas** [comment]
I wrote a function to take in fasta file path and output a file object
